name: loveloom
description: "A new Flutter project."
<<<<<<< HEAD
publish_to: 'none'
=======
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
>>>>>>> 2a137ea (Save current work before rebase)

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

<<<<<<< HEAD
  http: ^0.13.6
  flutter_secure_storage: ^8.0.0

  image_picker: 0.8.9
=======
  flutter_secure_storage: ^8.0.0
  intl: ^0.18.0

  image_picker: ^0.8.7+4
  dotted_border: ^2.0.0
>>>>>>> 2a137ea (Save current work before rebase)
  google_maps_flutter: ^2.3.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
<<<<<<< HEAD
  flutter_lints: ^6.0.0
=======
  flutter_lints: ^5.0.0
>>>>>>> 2a137ea (Save current work before rebase)

flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Italic-VariableFont_wght.ttf
  assets:
    - assets/Group 1171275043.png

  uses-material-design: true
